#El programa esta divido en 3 secciones: Inicio, Libros, Prestamos:
#Este es el cuerpo principal que invoca a la app y genera las estructuras

import tkinter as tk
from tkinter import ttk
from tkinter import messagebox as mb
from tkinter import PhotoImage
from tkinter import scrolledtext as st
import VentanasEmergentes as ve
import BD

class Biblioteca:
    def __init__(self):
        self.ventana = tk.Tk()
        self.ventana.title("Mi biblioteca")
        self.ventana.wm_iconbitmap("logo.ico")
        self.ventana.config(bg="#5c9396")
        self.ventana.bind('<Return>',self.consulta)
        self.cone = BD.ConnectionDB()
        self.cone.abrir()
        self.n = ttk.Style()
        self.n.configure('My.TNotebook', background='#9bc0b9')
        self.f = ttk.Style()
        self.f.configure('My.TFrame', background='#ccd9cf')
        self.cuadernogeneral = ttk.Notebook(self.ventana,style='My.TNotebook')
        self.cuadernogeneral.grid(column=0,row=0,padx=5,pady=5)
        self.inicio()
        self.libro()
        self.prestamo()
        self.ventana.mainloop()

    def inicio(self):
        self.pagina1 = ttk.Frame(self.cuadernogeneral,style='My.TFrame')
        self.cuadernogeneral.add(self.pagina1, text="Inicio")
        self.cartel11 = tk.Label(self.pagina1,text="¡Bienvenido!")
        self.cartel11.config(bg='#ccd9cf', font=("Gill Sans Light", 15), fg="#0b1828")
        self.cartel11.grid(column=0,row=0,padx=4,pady=4)

        self.cuadro11 = tk.LabelFrame(self.pagina1,text="Consultemos (oprima Enter)",background='#ccd9cf',fg="#0b1828",font=("Gill Sans Light", 10,"bold"))
        self.cuadro11.grid(column=0,row=1,padx=4,pady=4)
        self.label11 = tk.Label(self.cuadro11,text="Título",fg="#0b1828")
        self.label11.config(bg='#ccd9cf',font=("Gill Sans Light", 10), fg="black")
        self.label11.grid(column=0,row=0)
        self.dato11 = tk.StringVar()
        self.entry11 = tk.Entry(self.cuadro11,textvariable=self.dato11)
        self.entry11.grid(column=0,row=1)
        self.label12 = tk.Label(self.cuadro11,text="Autor")
        self.label12.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.label12.grid(column=1,row=0)
        self.dato12 = tk.StringVar()
        self.entry12 = tk.Entry(self.cuadro11,textvariable=self.dato12,state="readonly")
        self.entry12.grid(column=1,row=1)
        self.label13 = tk.Label(self.cuadro11,text="Edición")
        self.label13.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.label13.grid(column=2,row=0)
        self.dato13 = tk.StringVar()
        self.entry13 = tk.Entry(self.cuadro11,state="readonly",textvariable=self.dato13)
        self.entry13.grid(column=2,row=1)
        self.label14 = tk.Label(self.cuadro11,text="Lugar de impresión")
        self.label14.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.label14.grid(column=3,row=0)
        self.dato14 = tk.StringVar()
        self.entry14 = tk.Entry(self.cuadro11,state="readonly",textvariable=self.dato14)
        self.entry14.grid(column=3,row=1)
        self.label15 = tk.Label(self.cuadro11,text="Editorial")
        self.label15.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.label15.grid(column=0,row=2)
        self.dato15 = tk.StringVar()
        self.entry15 = tk.Entry(self.cuadro11,state="readonly",textvariable=self.dato15)
        self.entry15.grid(column=0,row=3)
        self.label16 = tk.Label(self.cuadro11,text="Traducido")
        self.label16.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.label16.grid(column=1,row=2)
        self.dato16 = tk.StringVar()
        self.entry16 = tk.Entry(self.cuadro11,state="readonly",textvariable=self.dato16)
        self.entry16.grid(column=1,row=3)
        self.label17 = tk.Label(self.cuadro11,text="Total de páginas")
        self.label17.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.label17.grid(column=2,row=2)
        self.dato17 = tk.StringVar()
        self.entry17 = tk.Entry(self.cuadro11,state="readonly",textvariable=self.dato17)
        self.entry17.grid(column=2,row=3)
        self.label18 = tk.Label(self.cuadro11,text="Condición")
        self.label18.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.label18.grid(column=3,row=2)
        self.dato18 = tk.StringVar()
        self.entry18 = tk.Entry(self.cuadro11,state="readonly",textvariable=self.dato18)
        self.entry18.grid(column=3,row=3)

        self.cuadro12 = tk.LabelFrame(self.pagina1,bd="0",bg='#ccd9cf')
        self.cuadro12.grid(column=0,row=2,padx=4,pady=4)
        self.cartel12 = tk.Label(self.cuadro12, text="Descarge toda la información aquí:")
        self.cartel12.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.cartel12.grid(column=0,row=0,padx=4,pady=4)
        self.boton11 = tk.Button(self.cuadro12,text="Justo aquí",bg='#9bc0b9',fg="#0b1828",command=self.exportar)
        self.boton11.grid(column=1,row=0,padx=4,pady=4)
    
    def libro(self):
        self.pagina2 = ttk.Frame(self.cuadernogeneral,style="My.TFrame")
        self.cuadernogeneral.add(self.pagina2, text="Libros")
        self.carter21 = tk.Label(self.pagina2,text="En esta sección podras realizar todas las tareas pertinentes a los libros que quiera \nadministrar, como ser:")
        self.carter21.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828",justify="left")
        self.carter21.grid(column=0,row=0,padx=4,pady=4)
        self.cuadro21 = tk.LabelFrame(self.pagina2,bg='#ccd9cf')
        self.cuadro21.grid(column=0,row=1,padx=4,pady=4)
        self.carter22 = tk.Label(self.cuadro21,text="Cargar los datos de un nuevo libro",justify="left")
        self.carter22.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.carter22.grid(column=0,row=0,padx=4,pady=4)
        self.boton22 = tk.Button(self.cuadro21,text="Cargar",command=self.cargarlibro,bg='#9bc0b9',fg="#0b1828")
        self.boton22.grid(column=1,row=0,padx=4,pady=4)
        self.carter23 = tk.Label(self.cuadro21,text="Modificar datos de un libro existente",justify="left")
        self.carter23.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.carter23.grid(column=0,row=1,padx=4,pady=4)
        self.boton23 = tk.Button(self.cuadro21,text="Modificar",command=self.modificarlibro,bg='#9bc0b9',fg="#0b1828")
        self.boton23.grid(column=1,row=1,padx=4,pady=4)
        self.carter24 = tk.Label(self.cuadro21,text="Eliminar un libro",justify="left")
        self.carter24.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.carter24.grid(column=0,row=2,padx=4,pady=4)
        self.boton24 = tk.Button(self.cuadro21,text="Eliminar",command=self.eliminarlibro,bg='#9bc0b9',fg="#0b1828")
        self.boton24.grid(column=1,row=2,padx=4,pady=4)
    def cargarlibro(self):
        cargar = ve.CargarLibro()
    def modificarlibro(self):
        modificar = ve.ModificarLibro()
    def eliminarlibro(self):
        eliminar = ve.EliminarLibro()
            
    def prestamo(self):
        self.pagina3 = ttk.Frame(self.cuadernogeneral,style = "My.TFrame")
        self.cuadernogeneral.add(self.pagina3, text="Préstamos")
        self.carter31 = tk.Label(self.pagina3,text="En esta sección podrás generar y comprobar todos los préstamos de la biblioteca:\n ")
        self.carter31.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828",justify="left")
        self.carter31.grid(column=0,row=0,padx=4,pady=4)
        self.cuadro31 = tk.LabelFrame(self.pagina3,bg='#ccd9cf')
        self.cuadro31.grid(column=0,row=1,padx=4,pady=4)
        self.carter32 = tk.Label(self.cuadro31,text="Generar un nuevo préstamo",justify="left")
        self.carter32.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.carter32.grid(column=0,row=0,padx=4,pady=4)
        self.boton32 = tk.Button(self.cuadro31,text="Cargar",command=self.cargarprestamo,bg='#9bc0b9',fg="#0b1828")
        self.boton32.grid(column=1,row=0,padx=4,pady=4)
        self.carter33 = tk.Label(self.cuadro31,text="Finalizar un préstamos existente",justify="left")
        self.carter33.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.carter33.grid(column=0,row=1,padx=4,pady=4)
        self.boton33 = tk.Button(self.cuadro31,text="Devolver",command=self.devolver,bg='#9bc0b9',fg="#0b1828")
        self.boton33.grid(column=1,row=1,padx=4,pady=4)
        self.cartel34 = tk.Label(self.cuadro31,text="Controlar préstamos actuales",justify="left")
        self.cartel34.config(bg='#ccd9cf', font=("Gill Sans Light", 10),fg="#0b1828")
        self.cartel34.grid(column=0,row=2,padx=4,pady=4)
        self.boton34 = tk.Button(self.cuadro31,text="Controlar",command=self.revisar,bg='#9bc0b9',fg="#0b1828")
        self.boton34.grid(column=1,row=2,padx=4,pady=4)
    def cargarprestamo(self):
        cargarp = ve.CargarPrestamo()
    def devolver(self):
        devolver = ve.Devolver()
    def revisar(self):
        revisar = ve.Revisar()

    def consulta(self,event):
        x = (self.dato11.get(),)
        lista = self.cone.consulta(x)
        print(lista)
        self.dato12.set(lista[0][0])
        self.dato13.set(lista[0][1])
        self.dato14.set(lista[0][2])
        self.dato15.set(lista[0][3])
        self.dato16.set(lista[0][4])
        self.dato17.set(lista[0][5])
        self.dato18.set(lista[0][6])
    def exportar(self):
        self.lista = self.cone.recuperar_todos()
        self.archivo = open("Biblioteca.txt","w")
        for x in self.lista:
            text = f"Título: {str(x[0])} Autor:{str(x[1])} Edición{str(x[2])} Impresión: {str(x[3])} Editorial: {str(x[4])} Traducción: {str(x[5])} Páginas: {str(x[6])} Condición: {str(x[7])}\n"
            self.archivo.write(text)
        self.archivo.close()
        mb.showinfo("Descarga completa","Toda la información se exporto en el directorio base")

libros = Biblioteca()